kind: Service
apiVersion: v1
metadata:
  name: myapp-feature-b
  labels:
    app: myapp-feature-b
spec:
  selector:
    app: myapp-feature-b
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 80
    name: myapp-feature-b
