kind: Service
apiVersion: v1
metadata:
  name: myapp-feature-c
  labels:
    app: myapp-feature-c
spec:
  selector:
    app: myapp-feature-c
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000
    name: application
