kind: Service
apiVersion: v1
metadata:
  name: myapp-feature-a
  labels:
    app: myapp-feature-a
spec:
  selector:
    app: myapp-feature-a
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000
    name: myapp-feature-a
