apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-feature-b
  labels:
    app: myapp-feature-b
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp-feature-b
  template:
    metadata:
      labels:
        app: myapp-feature-b
    spec:
      containers:
      - name: myapp-feature-b
        image: 366449471548.dkr.ecr.ap-south-1.amazonaws.com/myapp-feature-b:latest
        ports:
        - containerPort: 3000
      imagePullSecrets:
      - name: aws-registry
