name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag myapp
      
    - name: Push AWS ECR
      # You may pin to the exact commit or the version.
      # uses: hands-lab/push-ecr-action@18f19e41550f632ff0d8ce224a3ffd1e552d3598
      uses: hands-lab/push-ecr-action@v1.1
      with:
        # image name
        image: myapp
        # AWS Access Key ID
        aws-access-key-id: ${{ secrets.awsaccesskeyid }}
        # AWS Secret Access Key
        aws-secret-access-key: ${{ secrets.awssecretkeyid }}
        # AWS Region
        aws-region: ap-south-1
        # AWS Account ID
        aws-account-id: ${{ secrets.awsaccountid }}
        
    - name: Kubectl Apply
      # You may pin to the exact commit or the version.
      # uses: okteto/apply@4e27118456f347c5ef86dac30476118540dd5581
      uses: okteto/apply@v4.2
      with:
        # Path to the Kubernetes manifest. Can be a file or a directory
        manifest: myapp-deploy.yml
        # If present, the namespace scope for this action. If not specified, it will use the current context
        namespace: default
        
    - name: Kubectl Apply
      # You may pin to the exact commit or the version.
      # uses: okteto/apply@4e27118456f347c5ef86dac30476118540dd5581
      uses: okteto/apply@v4.2
      with:
        # Path to the Kubernetes manifest. Can be a file or a directory
        manifest: myappservice.yml
        # If present, the namespace scope for this action. If not specified, it will use the current context
        namespace: default
